# modify the paths appropriately
JDKPATH = /Library/java/JavaVirtualMachines/jdk1.8.0_92.jdk
LIBPATH = .:..
CLASSPATH = $(LIBPATH)
BINPATH = $(JDKPATH)/Contents/Home/bin
JAVAC = $(JDKPATH)/Contents/Home/bin/javac -classpath $(CLASSPATH)
JAVA  = $(JDKPATH)/Contents/Home/bin/java  -classpath $(CLASSPATH)

# test buffer manager

# BMTest:BMTest.java
#	$(JAVAC) TestDriver.java BMTest.java

# bmtest: BMTest
#	$(JAVA) tests.BMTest

# test disk manager

# DBTest:DBTest.java
#	$(JAVAC) TestDriver.java DBTest.java

# dbtest: DBTest
#	$(JAVA) tests.DBTest

# test heapfile 

# HFTest:HFTest.java
#	$(JAVAC) TestDriver.java HFTest.java

# hftest: HFTest
#	$(JAVA) tests.HFTest

# test btree

# BTTest:BTTest.java
#	$(JAVAC) TestDriver.java BTTest.java

# bttest: BTTest
#	$(JAVA) tests.BTTest

# test index

# IndexTest:IndexTest.java
#	$(JAVAC) TestDriver.java IndexTest.java

# indextest: IndexTest
#	$(JAVA) tests.IndexTest

# test join

# JoinTest:JoinTest.java
#	$(JAVAC) TestDriver.java JoinTest.java

# jointest: JoinTest
#	$(JAVA) tests.JoinTest

# test sort

# SortTest:SortTest.java
#	$(JAVAC) TestDriver.java SortTest.java

# sorttest: SortTest
#	$(JAVA) tests.SortTest

# test sortMerge

# SMJoin:SM_JoinTest.java
#	$(JAVAC) SM_JoinTest.java TestDriver.java

# sortmerge: SMJoin
#	$(JAVA) tests.SM_JoinTest

# test 1
Test1:Test1.java
	$(JAVAC) TestDriver.java Test1.java
	
test1: Test1
	$(JAVA) tests.Test1
	
# test 2
Test2:Test2.java
	$(JAVAC) TestDriver.java Test2.java

test2: Test2
	$(JAVA) tests.Test2
	
# test 3
Test3:Test3.java
	$(JAVAC)  TestDriver.java Test3.java
	
test3: Test3
	$(JAVA) tests.Test3
# test 4

# test 5

# test 6


